---
title: "Figure_3_cowplot"
output: html_document
---

# Plot figure2c

```{r}

library(ggtext)

fc_df <- readRDS('Fig3c_mss_data.rds')

p <- ggplot(fc_df, aes(x=SQ, y=reg)) + geom_point(color='black',fill=colors()[132], stroke=1, shape=21, alpha=0.55, size=3.8) 
p <- p+theme_bw() 
p <- p+theme_bw() + theme(text=element_text(family="Ubuntu Light", face="plain", size=15))

# Ticks
p <- p+theme(axis.ticks.length=unit(-0.10, "cm"), axis.text.x = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")), axis.text.y = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")))
p <- p+theme(axis.text=element_text(size=9.0),axis.title.x=element_text(size=10.0,face="plain"),axis.title.y=element_text(size=10.5,face="plain"),plot.title=element_text(size=9.75,face='bold'))
p <- p + xlab('Substrate quality') + ylab('log2-fc (median)') + ggtitle('Downregulation')
p <- p+theme(plot.title = element_text(hjust = 0.5))
p <- p + theme(panel.border= element_blank())
p <- p + theme(legend.title=element_text(size=8.5),legend.text = element_text(size=10))
p <- p + theme(axis.title.x = element_text(vjust=6.0))
p <- p+geom_richtext(data = fc_df[1,], x=0.65, y=-1.5, label='r<sub>s</sub> = -0.625',size=3.25,fontface='plain',col='black',label.color = NA, fill = NA)

figure_3c <- p

```


```{r}

# Put everything together with Cowplot

library(cowplot)

m <- ggdraw() + draw_image('Figure_3F_crop.png',width=1.0,height=1.0,clip='on',hjust=-0.03,vjust=0.035)
figure_3f <- plot_grid(m,greedy=F)

g1 <- plot_grid(figure_3a,figure_3b,figure_3c,ncol=3,nrow=1,align='h',rel_widths=c(0.725,1.1,0.775), labels=c('A','B','C'))

g2 <- plot_grid(figure_3d,figure_3e,figure_3f,ncol=3,nrow=1,rel_widths=c(0.85,0.85,1), labels=c('D','E','F'))

g3 <- plot_grid(g1,g2,nrow=2,align='v')

ggsave(file='/home/david/Documents/Work/CK2_revisions/Figure_3/Figure_3.pdf', plot=g3, width=8.5, height=5.5)

```

