---
title: "Figure_1"
author: "David Bradley"
date: "10/1/2020"
output: html_document
---

# GGplot font

```{r}

# https://stackoverflow.com/questions/27689222/changing-fonts-for-graphs-in-r

library(extrafont)
font_import()
loadfonts()       #Register fonts for Windows bitmap output
fonts() 

```

# Retrieve the CK2 substrates

```{r}

library(readr)
library(seqinr)
library(ggseqlogo)
library(gdata)

# Data comes from Bachmann et al., 2019 (https://www.biorxiv.org/content/10.1101/822668v3)

prot_mapper <- read_csv('export.csv')

# Kinases only

prot_mapper <- prot_mapper[unlist(prot_mapper[,5]) == TRUE,]

# Retrieve upstream kinase, substrate, and substrate position

ksr <- prot_mapper[,c(3,4,6,9,10)]

# We exclude KSRs that are supported only by the text-mining tools

curated <- c('psp','signor','pid','bel','reactome')

source_list <- strsplit(unlist(ksr[,5]),split=',')

number_curated <- lapply(source_list, function(x) length(intersect(x,curated)))

ksr <- ksr[which(number_curated > 0),]

# Correct formatting problems

for (i in 1:nrow(ksr)) {
 
  if(is.na(ksr[i,2])) {ksr[i,2] <- ksr[i,1]} 
  
}

# Retrieve CSNK2A1 and CSNK2A2 substrates

csnk2a1_ksr <- ksr[which(unlist(ksr[,2] == 'CSNK2A1') == TRUE),]
csnk2a2_ksr <- ksr[which(unlist(ksr[,2] == 'CSNK2A2') == TRUE),]
csnk2a_ksr <- unique(rbind(csnk2a1_ksr,csnk2a2_ksr)) 

hs_rp <- read.fasta('hs_proteome_uniprot.fasta', seqtype='AA')
hs_ids <- rapply(strsplit(names(hs_rp),split='\\|'),function(x) x[2])

# Retrieve the sequences

psite_vec <- NULL
index_vec <- NULL

for (i in 1:nrow(csnk2a_ksr)) {
  
  print(i)
  
  # Retrieve the first element only
  uniprot_id <- unname(unlist(csnk2a_ksr[i,3]))
  site_pos <- unname(unlist(csnk2a_ksr[i,4]))
  
  # Loop for ambiguous psite positions
  
  for (j in 1:length(uniprot_id)) {
    
    pos <- as.numeric(site_pos)
    
    # Substrate sequence
  
    sub_seq <- unlist(getSequence(hs_rp[hs_ids %in% uniprot_id[j]]))
    
    if (length(sub_seq) == 0) {next}
    
    # Phosphosite position
    
    if (pos < 8) {
      
      gap <- paste(rep('_',(8-pos)),collapse='')
      psite <- paste(sub_seq[1:(pos+7)],collapse='')
      psite <- paste(gap,psite,sep='')
      if (!substr(psite,8,8) %in% c('S','T','Y')) {next}
      psite_vec <- c(psite_vec, psite)
      index_vec <- c(index_vec, i)
      
    } else if ((pos+7) > length(sub_seq)) {
      
      psite <- paste(sub_seq[(pos-7):(length(sub_seq))],collapse='')
      gap <- paste(rep('_',(pos+7)-length(sub_seq)),collapse='')
      psite <- paste(psite,gap,sep='')
      if (!substr(psite,8,8) %in% c('S','T','Y')) {next}
      psite_vec <- c(psite_vec, psite)
      index_vec <- c(index_vec, i)
      
    } else {
      
      psite <- paste(sub_seq[(pos-7):(pos+7)],collapse='')
      if (!substr(psite,8,8) %in% c('S','T','Y')) {next}
      psite_vec <- c(psite_vec, psite)
      index_vec <- c(index_vec, i)
      
    }
  } 
}

# Remove potential heirarchical sites
bachmann_vec <- psite_vec
p1s <- rapply(strsplit(psite_vec,split=''), function(x) x[9]) == 'S'
p3s <- rapply(strsplit(psite_vec,split=''), function(x) x[11]) == 'S'
psite_no_heira <- psite_vec[!(p1s|p3s)]

# Write out the non-hierarchical phosphorylation sites obtained from the ProtMapper resource

write.table(psite_no_heira,'CK2_non_hierarchical_Bachmann.txt',col.names=F,row.names=F,quote=F)

```

# Generate a GG barplot for positions -6 to +6 (data was retrieved using the pLogo resource)
# To do this, we have to parse the output of pLogo (https://plogo.uconn.edu/)

```{r}

library(readr)
library(ggplot2)

pLogo_scores <- readLines('pLogo_CK2_non_hierarchical.txt')

D_scores <- pLogo_scores[grep('D_', pLogo_scores)]
D_scores <- parse_number(rapply(strsplit(D_scores,split='='), function(x) x[2]))
D_scores <- D_scores[2:13]

E_scores <- pLogo_scores[grep('E_', pLogo_scores)]
E_scores <- parse_number(rapply(strsplit(E_scores,split='='), function(x) x[2]))
E_scores <- E_scores[2:13]

col1 <- c(D_scores, E_scores)
col2 <- c(rep('D',length(D_scores)),rep('E',length(E_scores)))
col3 <- rep(factor(c(-6:-1,1:6)),2)

pLogo_DF <- data.frame(col1,col2,col3)
colnames(pLogo_DF) <- c('pLogo','AA','Position')

# Generate plot

p <- ggplot(data=pLogo_DF, aes(x=Position, y=pLogo, fill=AA)) + geom_bar(stat="identity", position=position_dodge())
p <- p+theme_bw() + theme(text=element_text(family="Ubuntu Light", face="plain", size=15))
p <- p + scale_fill_manual(values=c(colors()[225],colors()[180]))

# Ticks
p <- p+theme(axis.ticks.length=unit(-0.10, "cm"), axis.text.x = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")), axis.text.y = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")) )

p <- p + ylab("log-odds of the binomial probability") + xlab("Position") + ggtitle('CK2 substrates (D/E enrichment)')

p <- p + theme(legend.title = element_blank())

p <- p+theme(axis.text=element_text(size=9),axis.title.x=element_text(size=9,face="plain",vjust=4.5,margin = margin(t = 0, r = 0, b = 0, l = 0)),
             axis.title.y=element_text(size=9,face="plain"),plot.title=element_text(size=9,face='bold'))
p <- p+theme(plot.title = element_text(hjust = 0.5))
p <- p+  theme(legend.key.size = unit(0.4, 'cm'), legend.text = element_text(size=8), legend.margin=margin(t=0, r=0.1, b=0, l=-0.15, unit="cm"))


p <- p + geom_hline(yintercept=3.75, linetype="dashed", color = "red")

plogo_breaks <- c(-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6)

p <- p + scale_x_discrete(breaks=as.character(plogo_breaks),labels=c(plogo_breaks),
                          limits=as.character(plogo_breaks))

supp_fig_1a <- p
supp_fig_1a

ggsave(file='Supplementary_figure_1a.pdf', plot=p, width=6.0, height=4.8)

```

# Same plot but for the depletion of K/R

```{r}

library(readr)
library(ggplot2)

pLogo_scores <- readLines('pLogo_CK2_non_hierarchical.txt')

K_scores <- pLogo_scores[grep('K_', pLogo_scores)]
K_scores <- parse_number(rapply(strsplit(K_scores,split='='), function(x) x[2]))
K_scores <- K_scores[2:13]

R_scores <- pLogo_scores[grep('R_', pLogo_scores)]
R_scores <- parse_number(rapply(strsplit(R_scores,split='='), function(x) x[2]))
R_scores <- R_scores[2:13]

col1 <- c(K_scores, R_scores)
col2 <- c(rep('K',length(K_scores)),rep('R',length(R_scores)))
col3 <- rep(factor(c(-6:-1,1:6)),2)

pLogo_DF <- data.frame(col1,col2,col3)
colnames(pLogo_DF) <- c('pLogo','AA','Position')

# Generate plot

p <- ggplot(data=pLogo_DF, aes(x=Position, y=pLogo, fill=AA)) + geom_bar(stat="identity", position=position_dodge())
p <- p+theme_bw() + theme(text=element_text(family="Ubuntu Light", face="plain", size=15))
p <- p + scale_fill_manual(values=c(colors()[225],colors()[180]))

# Ticks
p <- p+theme(axis.ticks.length=unit(-0.10, "cm"), axis.text.x = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")), axis.text.y = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")) )

p <- p + ylab("log-odds of the binomial probability") + xlab("Position") + ggtitle('CK2 substrates (K/R depletion)')

p <- p + theme(legend.title = element_blank())

p <- p+theme(axis.text=element_text(size=9),axis.title.x=element_text(size=9,face="plain",vjust=4.5,margin = margin(t = 0, r = 0, b = 0, l = 0)),
             axis.title.y=element_text(size=9,face="plain"),plot.title=element_text(size=9,face='bold'))
p <- p+theme(plot.title = element_text(hjust = 0.5))
p <- p+  theme(legend.key.size = unit(0.4, 'cm'), legend.text = element_text(size=8), legend.margin=margin(t=0, r=0.1, b=0, l=-0.15, unit="cm"))

p <- p + geom_hline(yintercept=-3.75, linetype="dashed", color = "red")

plogo_breaks <- c(-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6)

p <- p + scale_x_discrete(breaks=as.character(plogo_breaks),labels=c(plogo_breaks),
                          limits=as.character(plogo_breaks))


supp_fig_1b <- p
supp_fig_1b

ggsave(file='Supplementary_figure_1b.pdf', plot=p, width=6.0, height=4.8)

```



