---
title: "Supplementary figure 1b"
author: "David Bradley"
date: "2/11/2020"
output: html_document
---

# GGplot font

```{r}

# https://stackoverflow.com/questions/27689222/changing-fonts-for-graphs-in-r

library(extrafont)

font_import()
loadfonts()       #Register fonts for Windows bitmap output
fonts() 

```

# Parse out the CK2 degenrate peptide array results from Hutti et al., 2004

```{r}

# Read in the PDF of the CK2 array from Hutti et al., 2004

library(pdftools)
Hutti_CK2 <- pdftools::pdf_text(pdf = "https://static-content.springer.com/esm/art%3A10.1038%2Fnmeth708/MediaObjects/41592_2004_BFnmeth708_MOESM2_ESM.pdf")

Hutti_CK2 <- strsplit(Hutti_CK2[6],split='\n')[[1]][3:22]
Hutti_AAs <- rapply(strsplit(Hutti_CK2,split=''),function(x) x[1])
Hutti_CK2 <- rapply(stringr::str_extract_all(Hutti_CK2, "[[:digit:]]+\\.*[[:digit:]]*"), function(x) as.numeric(x))

Hutti_CK2 <- matrix(Hutti_CK2,nrow=20,ncol=9,byrow=T)
colnames(Hutti_CK2) <- c('-5','-4','-3','-2','-1','+1','+2','+3','+4')
rownames(Hutti_CK2) <- Hutti_AAs
vec <- c('P','G','A','C','S','T','V','I','L','M','F','Y','W','H','K','R','Q','N','D','E')

# Phosphoacceptor
Hutti_CK2 <- cbind(Hutti_CK2[,1:5],rep(0,20),Hutti_CK2[,6:9])
colnames(Hutti_CK2) <- c('-5','-4','-3','-2','-1','0','+1','+2','+3','+4')

# Function to calculate the substrate quality of phosphosites on the basis of the data derived from Hutti et al., 2004

ED_Hutti <- function(psite,pwm) {
  
  neg_row <- apply(pwm[rownames(pwm) %in% c('D','E'),],2,sum)
  pwm <- pwm[!rownames(pwm) %in% c('D','E'),]
  pwm <- rbind(pwm,neg_row)
  rownames(pwm)[nrow(pwm)] <- 'DE'
  
  psite <- unlist(strsplit(psite,split=''))
  
  c=0
  min=0
  
  # Ignore the central residue
  for (i in c(1:5,7:10)) {
    
    aa <- psite[i]  
    if (aa %in% c('D','E')) {aa <- 'DE'}
    # Skip if the amino acid is not D or E
    if (!(aa %in% c('DE'))) {next}
    
    current <- pwm[rownames(pwm) %in% aa,i]
    c = c+current
  
  }
  
  #maximum <- sum(apply(pwm[,c(1:5,7:10)],2,max))
  maximum <- sum(unname(pwm[rownames(pwm) %in% 'DE',]))
  mss = c/maximum
  
  return(unname(mss))
  
}

```

# Explore relationship between substrate quality and phosphorylation stoichiometry measured in Tsai et al., 2015

```{r}

setwd("~/Documents/Work/Stoichiometry/Figure_1")

library(gdata)
library(ggseqlogo)
library(ggplot2)
library(stringr)

Ishi <- read.xls('Ishihama_stoichiometry.xlsx',sheet=2, stringsAsFactors=FALSE)

## Exclude sites with 0 stoichiometry
Ishi <- Ishi[!Ishi[,8] == 0,]

Ishi_CK2 <- Ishi[grep('CK2',Ishi[,18]),]

# Doubly phosphorylated peptides confound stoichiometry analysis and should be removed
Ishi_CK2 <- Ishi_CK2[!Ishi_CK2[,3] == '2 Phospho (ST)',]

# Score all non-hierarchical sites with the MSS and then plot

Ishi_CK2_stoi <- Ishi_CK2[,c(8,9)]

# Remove all potential heirarchical sites and T sites
p1s <- rapply(strsplit(Ishi_CK2_stoi[,2],split=''), function(x) x[8]) == 'S'
p3s <- rapply(strsplit(Ishi_CK2_stoi[,2],split=''), function(x) x[10]) == 'S'
p0t <- rapply(strsplit(Ishi_CK2_stoi[,2],split=''), function(x) x[7]) == 'T'
Ishi_CK2_stoi <- Ishi_CK2_stoi[!(p1s|p3s|p0t),]

# Measure substrate quality from -5 to +4

mss_vec <- NULL

for (i in 1:nrow(Ishi_CK2_stoi)) {
  
  mss <- NULL
  ck2_site <- substr(Ishi_CK2_stoi[i,2],2,11)
  mss <- ED_Hutti(ck2_site,Hutti_CK2)
  if (length(mss) == 0) {break}
  mss_vec <- c(mss_vec, mss)
  
}

Ishi_CK2_stoi <- cbind(Ishi_CK2_stoi, mss_vec)

### Boxplot MSS

ED_list <- list()
col1 <- NULL
col2 <- NULL
col3 <- NULL

for (i in 0:9) {
  
  lower <- 0.1*i
  upper <- lower+0.1
  print(lower)
  print(upper)
  
  ED_stoi <- Ishi_CK2_stoi[Ishi_CK2_stoi[,3] > lower & Ishi_CK2_stoi[,3] <= upper,1]
  ED_stoi <- ED_stoi[!ED_stoi == 'NaN']
  ED_list <- c(ED_list, list(ED_stoi))
  
  col1 <- c(col1,ED_stoi)
  col2 <- c(col2,rep(paste(lower,'-',upper,sep=''),length(ED_stoi)))
  col3 <- c(col3,Ishi_CK2_stoi[Ishi_CK2_stoi[,3] > lower & Ishi_CK2_stoi[,3] <= upper,2])
}

mss_data <- data.frame(col1,col2,stringsAsFactors = FALSE)
mss_data[,2] <- as.factor(mss_data[,2])
colnames(mss_data) <- c('Stoichiometry','Positions')

p <- ggplot(mss_data, aes(x=Positions, y=Stoichiometry)) + geom_boxplot(fill='white',color=colors()[35], lwd=1.15, notch=FALSE,fatten=0.75) + geom_jitter(width = 0.2, color=colors()[35],size=0.6) #colors()[123]

# Font
p <- p+theme_bw() + theme(text=element_text(family="Ubuntu Light", face="plain", size=15), panel.border = element_rect(color="black", size=1.2, linetype="solid"))

# Ticks
p <- p+theme(axis.ticks.length=unit(-0.10, "cm"), axis.text.x = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")), axis.text.y = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")) )

p <- p + ylab("Stoichiometry") + xlab("Substrate quality") + ggtitle('CK2 (peptide array)')
p <- p + theme(axis.title.y = element_text(vjust=-1.5))
p <- p+theme(axis.text=element_text(size=7),axis.title.x=element_text(size=10,face="plain",vjust=3.5),
             axis.title.y=element_text(size=10,face="plain"),plot.title=element_text(size=10,face='bold',vjust=-1.5))
p <- p+theme(plot.title = element_text(hjust = 0.5))
p <- p + theme(legend.position = "none") # axis.line = element_blank(), panel.border = element_blank()) 
p <- p + theme(plot.margin = unit(c(0,0,0.1,0), "cm")) # t, r, b, l
p <- p + theme(axis.text.x = element_text(angle = 30, vjust = 1.0, hjust=1))
b1 <- p

supp_fig_1b <- p
supp_fig_1b

ggsave(file='Supplementary_figure_1B.pdf', plot=p, width=6.0, height=4.8)

```

