---
title: "Figure_5e"
author: "David Bradley"
date: '2023-05-19'
output: html_document
---

```{r}

# https://stackoverflow.com/questions/27689222/changing-fonts-for-graphs-in-r

library(extrafont)

font_import()
loadfonts()       #Register fonts for Windows bitmap output
fonts() 

```


```{r}

library(ggplot2)
library(gdata)
library(readxl)
library(seqinr)
library(stringr)

## replicate 1

clip170_data_rep1 <- read_xlsx('Supplementary_table_8.xlsx', skip=1, col_names=TRUE, sheet=1)
clip170_data_rep1 <- as.data.frame(clip170_data_rep1)

# Remove missing values
wt_rep1 <- clip170_data_rep1[!is.na(clip170_data_rep1[,1]),1]
mut1_rep1 <- clip170_data_rep1[!is.na(clip170_data_rep1[,2]),2]
mut2_rep1 <- clip170_data_rep1[!is.na(clip170_data_rep1[,3]),3]
mut3_rep1 <- clip170_data_rep1[!is.na(clip170_data_rep1[,4]),4]
mut4_rep1 <- clip170_data_rep1[!is.na(clip170_data_rep1[,5]),5]

# normalise all values with respect to the mean of the WT (for this replicate)

wt_rep1_mean <- mean(wt_rep1)

wt_rep1_norm <- wt_rep1/(wt_rep1_mean)
mut1_rep1_norm <- mut1_rep1/(wt_rep1_mean)
mut2_rep1_norm <- mut2_rep1/(wt_rep1_mean)
mut3_rep1_norm <- mut3_rep1/(wt_rep1_mean)
mut4_rep1_norm <- mut4_rep1/(wt_rep1_mean)

# replicate 2

clip170_data_rep2 <- read_xlsx('Supplementary_table_8.xlsx', skip=1, col_names=TRUE, sheet=2)
clip170_data_rep2 <- as.data.frame(clip170_data_rep2)

# Remove missing values
wt_rep2 <- clip170_data_rep2[!is.na(clip170_data_rep2[,1]),1]
mut1_rep2 <- clip170_data_rep2[!is.na(clip170_data_rep2[,2]),2]
mut2_rep2 <- clip170_data_rep2[!is.na(clip170_data_rep2[,3]),3]
mut3_rep2 <- clip170_data_rep2[!is.na(clip170_data_rep2[,4]),4]
mut4_rep2 <- clip170_data_rep2[!is.na(clip170_data_rep2[,5]),5]

# normalise all values with respect to the mean of the WT (for this replicate)

wt_rep2_mean <- mean(wt_rep2)

wt_rep2_norm <- wt_rep2/(wt_rep2_mean)
mut1_rep2_norm <- mut1_rep2/(wt_rep2_mean)
mut2_rep2_norm <- mut2_rep2/(wt_rep2_mean)
mut3_rep2_norm <- mut3_rep2/(wt_rep2_mean)
mut4_rep2_norm <- mut4_rep2/(wt_rep2_mean)

# replicate 3

clip170_data_rep3 <- read_xlsx('Supplementary_table_8.xlsx', skip=1, col_names=TRUE, sheet=3)
clip170_data_rep3 <- as.data.frame(clip170_data_rep3)

# Remove missing values
wt_rep3 <- clip170_data_rep3[!is.na(clip170_data_rep3[,1]),1]
mut1_rep3 <- clip170_data_rep3[!is.na(clip170_data_rep3[,2]),2]
mut2_rep3 <- clip170_data_rep3[!is.na(clip170_data_rep3[,3]),3]
mut3_rep3 <- clip170_data_rep3[!is.na(clip170_data_rep3[,4]),4]
mut4_rep3 <- clip170_data_rep3[!is.na(clip170_data_rep3[,5]),5]

# normalise all values with respect to the mean of the WT (for this replicate)

wt_rep3_mean <- mean(wt_rep3)

wt_rep3_norm <- wt_rep3/(wt_rep3_mean)
mut1_rep3_norm <- mut1_rep3/(wt_rep3_mean)
mut2_rep3_norm <- mut2_rep3/(wt_rep3_mean)
mut3_rep3_norm <- mut3_rep3/(wt_rep3_mean)
mut4_rep3_norm <- mut4_rep3/(wt_rep3_mean)

# replicate 4

clip170_data_rep4 <- read_xlsx('Supplementary_table_8.xlsx', skip=1, col_names=TRUE, sheet=4)
clip170_data_rep4 <- as.data.frame(clip170_data_rep4)

# Remove missing values
wt_rep4 <- clip170_data_rep4[!is.na(clip170_data_rep4[,1]),1]
mut1_rep4 <- clip170_data_rep4[!is.na(clip170_data_rep4[,2]),2]
mut2_rep4 <- clip170_data_rep4[!is.na(clip170_data_rep4[,3]),3]
mut3_rep4 <- clip170_data_rep4[!is.na(clip170_data_rep4[,4]),4]
mut4_rep4 <- clip170_data_rep4[!is.na(clip170_data_rep4[,5]),5]

# normalise all values with respect to the mean of the WT (for this replicate)

wt_rep4_mean <- mean(wt_rep4)

wt_rep4_norm <- wt_rep4/(wt_rep4_mean)
mut1_rep4_norm <- mut1_rep4/(wt_rep4_mean)
mut2_rep4_norm <- mut2_rep4/(wt_rep4_mean)
mut3_rep4_norm <- mut3_rep4/(wt_rep4_mean)
mut4_rep4_norm <- mut4_rep4/(wt_rep4_mean)

## Pool results from across replicates for each genotype (WT, Mut1, Mut2, Mut3, and Mut4)

a <- c(wt_rep1_norm,wt_rep2_norm,wt_rep3_norm,wt_rep4_norm) # WT
b <- c(mut1_rep1_norm,mut1_rep2_norm,mut1_rep3_norm,mut1_rep4_norm) # Mut1
c <- c(mut2_rep1_norm,mut2_rep2_norm,mut2_rep3_norm,mut2_rep4_norm) # Mut2
d <- c(mut3_rep1_norm,mut3_rep2_norm,mut3_rep3_norm,mut3_rep4_norm) # Mut3
e <-  c(mut4_rep1_norm,mut4_rep2_norm,mut4_rep3_norm,mut4_rep4_norm) #Mut4
  
```

# Swarm plot

```{r}

library(ggplot2)
library(ggbeeswarm)
library(viridis)
library(ggsignif)

# Reformat the data into a 'long' data frame format that can be used for ggplots

col1 <- c(a,b,c,d,e)
col2 <- c(rep('WT',length(a)),rep('Mut1',length(b)),rep('Mut2',length(c)),rep('Mut3',length(d)),rep('Mut4',length(e)))
col3_wt <- c(rep('rep1',length(wt_rep1)),rep('rep2',length(wt_rep2)),rep('rep3',length(wt_rep3)),rep('rep4',length(wt_rep4)))
col3_mut1 <- c(rep('rep1',length(mut1_rep1)),rep('rep2',length(mut1_rep2)),rep('rep3',length(mut1_rep3)),rep('rep4',length(mut1_rep4)))
col3_mut2 <- c(rep('rep1',length(mut2_rep1)),rep('rep2',length(mut2_rep2)),rep('rep3',length(mut2_rep3)),rep('rep4',length(mut2_rep4)))
col3_mut3 <- c(rep('rep1',length(mut3_rep1)),rep('rep2',length(mut3_rep2)),rep('rep3',length(mut3_rep3)),rep('rep4',length(mut3_rep4)))
col3_mut4 <- c(rep('rep1',length(mut4_rep1)),rep('rep2',length(mut4_rep2)),rep('rep3',length(mut4_rep3)),rep('rep4',length(mut4_rep4)))
col3 <- c(col3_wt,col3_mut1,col3_mut2,col3_mut3,col3_mut4)

###

df <- data.frame(col1,col2,col3)
colnames(df) <- c('binding','genotype','replicates')
df$genotype = factor(df$genotype, levels=c('WT','Mut1','Mut2','Mut3','Mut4'))

median.quartile <- function(x){
  out <- quantile(x, probs = c(0.25,0.5,0.75))
  names(out) <- c("ymin","y","ymax")
  return(out) 
}

mean.quartile <- function(x){
  out <- median(x)
  names(out) <- c("y")
  return(out) 
}

p <- ggplot(df, aes(x = genotype, y = binding, color=replicates)) +geom_beeswarm(color='grey',cex=0.78)
p <- p+theme_bw()
p <- p+theme_bw() + theme(text=element_text(family="Ubuntu Light", face="plain"))
p <- p + stat_summary(fun.data=median.quartile, geom="pointrange", lwd=0.5,position=position_dodge2(width = 0.25),alpha=0.45)
p <- p+scale_color_manual(values=viridis(5)[2:5])
p <- p+xlab('')+ylab('CLIP-170 \n normalised on CENP-C')
p <- p + stat_summary(fun.y = median, geom = 'point', size = 12, shape = '_', color='black', linetype='dashed')
p <- p+theme(axis.text=element_text(size=16),axis.title.x=element_text(size=16,face="plain"),axis.title.y=element_text(size=19,face="bold"),plot.title=element_text(size=18,face='bold'))
p <- p + theme(panel.border= element_blank())
p <- p + theme(legend.text=element_text(size=12),legend.title = element_text(size=13))
p <- p+theme(legend.margin=margin(0,0,0,0),legend.box.margin=margin(-10,-2,-10,-10))
p <- p + theme(axis.ticks.x = element_line(color = c(NA, NA, NA, NA,NA)))
p <- p + geom_signif(y_position = c(5.1), xmin = c(0.95), 
              xmax = c(5.05), annotation = c("p << 0.01"),tip_length = c(0.075,0.02),col='black',textsize=4.95)
p <- p + geom_signif(y_position = c(5.1,5.1,5.1), xmin = c(2,3,4), 
              xmax = c(2,3,4), annotation = c('','',''),tip_length = c(0.02,0.02,0.02),col='black',textsize=4.95)
p <- p + geom_signif(y_position = c(4.44), xmin = c(2), 
              xmax = c(5), annotation = c("p = 0.038"),tip_length = c(0.02,0.02),col='black',textsize=4.95)
p <- p + geom_signif(y_position = c(3.75), xmin = c(3), 
              xmax = c(5), annotation = c("p = 0.0017"),tip_length = c(0.02,0.02),col='black',textsize=4.95)
p <- p+geom_text(data=data.frame(), aes(x=c(1:5), y=rep(5.6,5)), label=c(unname(table(df[,2]))),col=colors()[190], fontface='plain', size=5.20)
p

ggsave(file='Figure_5e_normalised_with_samples.pdf', plot=p, width=7.15, height=6.1)
ggsave(file='Figure_5e.png', plot=p, width=7.6, height=6.0)

#p <- ggplot(df, aes(x = col2, y = col1, color=col3)) +geom_beeswarm()

```

# anova and Tukey's honest test

```{r}

aov_test <- aov(col1 ~ col2, data = df)
tt <- TukeyHSD(aov_test)
tt$f[,"p adj"]
print(tt,digits=15)

```



