---
title: "Figure_5d"
author: "David Bradley"
date: '2023-05-19'
output: html_document
---

```{r}

# https://stackoverflow.com/questions/27689222/changing-fonts-for-graphs-in-r

library(extrafont)

font_import()
loadfonts()       #Register fonts for Windows bitmap output
fonts() 

```


```{r}

library(ggplot2)

# These numbers come from supplementary table 7 (sheet 1)

col1 <- c('A','B','C','D','E')
col2 <- c(log(209301.76,base=10),log(14145.55,base=10),log(59805.79,base=10),log(554240.34,base=10),log(1030591.03,base=10))

df <- data.frame(col1,col2)

g <- ggplot(df, aes(x=col1,y=col2))+geom_bar(stat='identity',width=0.32)
g <- g+coord_cartesian(ylim=c(3.5,6.05))
g <- g+xlab('')+ylab('log10 (phospho-signal)')
g <- g+theme_bw()
g <- g + theme(text=element_text(family="Ubuntu Light", face="plain", size=15), panel.border = element_rect(color="black", size=1.2, linetype="solid"))+theme(legend.position="none")

g <- g+theme(axis.text=element_text(size=7),axis.title.x=element_text(size=10,face="plain"),axis.title.y=element_text(size=11,face="plain"),plot.title=element_text(size=12,face='bold'))

g <- g + theme(panel.border= element_blank())

ggsave(file='Figure_5d.pdf', plot=g, width=4.0, height=2.8)

```


