---
title: "Supplementary figure 3b"
author: "David Bradley"
date: "10/1/2020"
output: html_document
---

## Model the specificity of CK2 by retrieving
## the sequences of the known substrates 

```{r}

library(readr)
library(seqinr)
library(ggseqlogo)
library(gdata)

# Data comes from Bachmann et al., 2019 (https://www.biorxiv.org/content/10.1101/822668v3)

prot_mapper <- read_csv('export.csv')

# Kinases only

prot_mapper <- prot_mapper[unlist(prot_mapper[,5]) == TRUE,]

# Retrieve upstream kinase, substrate, and substrate position

ksr <- prot_mapper[,c(3,4,6,9,10)]

# We exclude KSRs that are supported only by the text-mining tools

curated <- c('psp','signor','pid','bel','reactome')

source_list <- strsplit(unlist(ksr[,5]),split=',')

number_curated <- lapply(source_list, function(x) length(intersect(x,curated)))

ksr <- ksr[which(number_curated > 0),]

# Correct formatting problems

for (i in 1:nrow(ksr)) {
 
  if(is.na(ksr[i,2])) {ksr[i,2] <- ksr[i,1]} 
  
}

# Retrieve CSNK2A1 and CSNK2A2 substrates

csnk2a1_ksr <- ksr[which(unlist(ksr[,2] == 'CSNK2A1') == TRUE),]
csnk2a2_ksr <- ksr[which(unlist(ksr[,2] == 'CSNK2A2') == TRUE),]
csnk2a_ksr <- unique(rbind(csnk2a1_ksr,csnk2a2_ksr)) 

hs_rp <- read.fasta('hs_proteome_uniprot.fasta', seqtype='AA')
hs_ids <- rapply(strsplit(names(hs_rp),split='\\|'),function(x) x[2])

# Retrieve the sequences

psite_vec <- NULL
index_vec <- NULL

for (i in 1:nrow(csnk2a_ksr)) {
  
  print(i)
  
  # Retrieve the first element only
  uniprot_id <- unname(unlist(csnk2a_ksr[i,3]))
  site_pos <- unname(unlist(csnk2a_ksr[i,4]))
  
  # Loop for ambiguous psite positions
  
  for (j in 1:length(uniprot_id)) {
    
    pos <- as.numeric(site_pos)
    
    # Substrate sequence
  
    sub_seq <- unlist(getSequence(hs_rp[hs_ids %in% uniprot_id[j]]))
    
    if (length(sub_seq) == 0) {next}
    
    # Phosphosite position
    
    if (pos < 8) {
      
      gap <- paste(rep('_',(8-pos)),collapse='')
      psite <- paste(sub_seq[1:(pos+7)],collapse='')
      psite <- paste(gap,psite,sep='')
      if (!substr(psite,8,8) %in% c('S','T','Y')) {next}
      psite_vec <- c(psite_vec, psite)
      index_vec <- c(index_vec, i)
      
    } else if ((pos+7) > length(sub_seq)) {
      
      psite <- paste(sub_seq[(pos-7):(length(sub_seq))],collapse='')
      gap <- paste(rep('_',(pos+7)-length(sub_seq)),collapse='')
      psite <- paste(psite,gap,sep='')
      if (!substr(psite,8,8) %in% c('S','T','Y')) {next}
      psite_vec <- c(psite_vec, psite)
      index_vec <- c(index_vec, i)
      
    } else {
      
      psite <- paste(sub_seq[(pos-7):(pos+7)],collapse='')
      if (!substr(psite,8,8) %in% c('S','T','Y')) {next}
      psite_vec <- c(psite_vec, psite)
      index_vec <- c(index_vec, i)
      
    }
  } 
}

# After removing potential heirarchical sites
bachmann_vec <- psite_vec
p1s <- rapply(strsplit(psite_vec,split=''), function(x) x[9]) == 'S'
p3s <- rapply(strsplit(psite_vec,split=''), function(x) x[11]) == 'S'
psite_no_heira <- psite_vec[!(p1s|p3s)]

# Retrieve the corresponding database records

csnk2a_ksr_no_heira <- csnk2a_ksr[index_vec[!(p1s|p3s)],]
csnk2a_ksr_no_heira <- cbind(csnk2a_ksr_no_heira,psite_no_heira)

# Iterate through each phosphosite and count the number of upstream kinases that are recorded in ProtMapper

kin_vec <- NULL

for (i in 1:nrow(csnk2a_ksr_no_heira)) {
  
  substrate <- csnk2a_ksr_no_heira[i,3]
  pos <- csnk2a_ksr_no_heira[i,4]
  
  # Retrieve all records
  
  ksr_records <- ksr[ksr[,3] == substrate & ksr[,4] == pos,]
  
  # Upstream kinases
  
  upstream_kinases <- unname(unlist(ksr_records[,2]))
  upstream_kinases <- setdiff(upstream_kinases,c('CSNK2A1','CSNK2A2'))
  upstream_no <- length(unique(upstream_kinases))
  
  kin_vec <- c(kin_vec, upstream_no)
  
}

csnk2a_ksr_no_heira <- cbind(csnk2a_ksr_no_heira, kin_vec)

```

# Calculate the CK2 substrate quality for each phosphosite

```{r}

# Generate the PWM

source('match-tm.r')
csnk2_pwm <- makePWM(substr(psite_no_heira,2,14))
ggseqlogo(substr(psite_no_heira,2,14),method='probability')

# Scoring function to calculate CK2 substrate quality

ED_weight <- function(psite,pwm) {
  
  neg_row <- apply(pwm[rownames(pwm) %in% c('D','E'),],2,sum)
  pwm <- pwm[!rownames(pwm) %in% c('D','E'),]
  pwm <- rbind(pwm,neg_row)
  rownames(pwm)[nrow(pwm)] <- 'DE'
  
  psite <- unlist(strsplit(psite,split=''))
  
  c=0
  min=0
  
  # Ignore the central residue
  for (i in c(1:6,8:13)) {
    
    aa <- psite[i]  
    if (aa %in% c('D','E')) {aa <- 'DE'}
    
    # Skip if the amino acid is not D or E
    if (!(aa %in% c('DE'))) {next}
    
    current <- pwm[rownames(pwm) %in% aa,i]
    c = c+current
  
  }
  
  maximum <- sum(pwm[rownames(pwm) == 'DE',][c(1:6,8:13)])
  mss = c/maximum
  
  return(unname(mss))
  
}

mss_vec <- NULL

for (i in 1:length(psite_no_heira)) {
  
  mss <- NULL
  ck2_site <- substr(psite_no_heira[i],2,14)
  mss <- ED_weight(ck2_site,csnk2_pwm)
  if (length(mss) == 0) {break}
  mss_vec <- c(mss_vec, mss)
  
}

csnk2a_ksr_no_heira <- cbind(csnk2a_ksr_no_heira, mss_vec)

# Remove sites with 0 substrate quality

csnk2a_ksr_no_heira <- csnk2a_ksr_no_heira[csnk2a_ksr_no_heira$mss_vec > 0,]

```

# Plot the relationship between substrate quality and promiscuity

```{r}

p <- ggplot(csnk2a_ksr_no_heira,aes(x=mss_vec,y=kin_vec)) + geom_point(size=0.85) # Warning message is for sites with NA promiscuity 
p <- p+theme_bw() + theme(text=element_text(family="Ubuntu Light", face="plain", size=15))
p <- p+theme(panel.border = element_blank())
p <- p + coord_cartesian(xlim=c(0,1))
p <- p + xlab('Substrate quality') + ylab('Substrate promiscuity (known)')

# Ticks
p <- p+theme(axis.ticks.length=unit(-0.10, "cm"), axis.text.x = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")), axis.text.y = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")) )

# Margins
p <- p + theme(plot.margin = unit(c(0,1.5,0.5,0.2), "cm")) # t, r, b, l

p <- p+theme(axis.text.x=element_text(size=9.5),axis.text.y=element_text(size=10.5),axis.title.x=element_text(size=11.5,face="plain"),axis.title.y=element_text(size=10.75,face="plain"),plot.title=element_text(size=18,face='bold'))

supp_fig_3b <- p

```


# Cowplot

```{r}

library(cowplot)

supp_fig_6 <- plot_grid(supp_fig_6a, supp_fig_6b, ncol = 2, align = "h",labels=c('a','b'))

ggsave(file='Supplementary_figure_6.pdf', plot=supp_fig_6, width=6.0, height=3.25)

```



