---
title: "Figure_1"
author: "David Bradley"
date: "10/1/2020"
output: html_document
---

# CK2-peptide model

```{r}

## PyMOL commands for generating CK2-peptide model

# fetch 2w06

# fetch 3war

## align DYRK with CK2

# align 2wo6, 3war

# remove chain B in 2wo6

# save CK2_peptide

# Mutate using the 'mutagenesis' wizard in PyMol

# Energy minimisation using Chiron

```

# GGplot font

```{r}

# https://stackoverflow.com/questions/27689222/changing-fonts-for-graphs-in-r

library(extrafont)

font_import()
loadfonts()       #Register fonts for Windows bitmap output
fonts() 

```

# Extract CK2 substrates and write Supplementary Table 1 

```{r}

library(readr)
library(seqinr)
library(ggseqlogo)
library(gdata)

# Kinase-substrate relationship data comes from Bachmann et al., 2019 (https://www.biorxiv.org/content/10.1101/822668v3)

prot_mapper <- read_csv('export.csv')

# Kinases only

prot_mapper <- prot_mapper[unlist(prot_mapper[,5]) == TRUE,]

# Retrieve upstream kinase, substrate, and substrate position

ksr <- prot_mapper[,c(3,4,6,9,10)]

# We exclude KSRs that are supported only by the text-mining tools

curated <- c('psp','signor','pid','bel','reactome')

source_list <- strsplit(unlist(ksr[,5]),split=',')

number_curated <- lapply(source_list, function(x) length(intersect(x,curated)))

ksr <- ksr[which(number_curated > 0),]

# Correct formatting problems

for (i in 1:nrow(ksr)) {
 
  if(is.na(ksr[i,2])) {ksr[i,2] <- ksr[i,1]} 
  
}

# Retrieve CSNK2A1 and CSNK2A2 substrates

csnk2a1_ksr <- ksr[which(unlist(ksr[,2] == 'CSNK2A1') == TRUE),]
csnk2a2_ksr <- ksr[which(unlist(ksr[,2] == 'CSNK2A2') == TRUE),]
csnk2a_ksr <- unique(rbind(csnk2a1_ksr,csnk2a2_ksr)) 

hs_rp <- read.fasta('hs_proteome_uniprot.fasta', seqtype='AA')
hs_ids <- rapply(strsplit(names(hs_rp),split='\\|'),function(x) x[2])

# Retrieve the phosphosite flanking sequences

psite_vec <- NULL
index_vec <- NULL

for (i in 1:nrow(csnk2a_ksr)) {
  
  print(i)
  
  # Retrieve the first element only
  uniprot_id <- unname(unlist(csnk2a_ksr[i,3]))
  site_pos <- unname(unlist(csnk2a_ksr[i,4]))
  
  # Loop for ambiguous psite positions
  
  for (j in 1:length(uniprot_id)) {
    
    pos <- as.numeric(site_pos)
    
    # Substrate sequence
  
    sub_seq <- unlist(getSequence(hs_rp[hs_ids %in% uniprot_id[j]]))
    
    if (length(sub_seq) == 0) {next}
    
    # Phosphosite position
    
    if (pos < 8) {
      
      gap <- paste(rep('_',(8-pos)),collapse='')
      psite <- paste(sub_seq[1:(pos+7)],collapse='')
      psite <- paste(gap,psite,sep='')
      if (!substr(psite,8,8) %in% c('S','T','Y')) {next}
      psite_vec <- c(psite_vec, psite)
      index_vec <- c(index_vec, i)
      
    } else if ((pos+7) > length(sub_seq)) {
      
      psite <- paste(sub_seq[(pos-7):(length(sub_seq))],collapse='')
      gap <- paste(rep('_',(pos+7)-length(sub_seq)),collapse='')
      psite <- paste(psite,gap,sep='')
      if (!substr(psite,8,8) %in% c('S','T','Y')) {next}
      psite_vec <- c(psite_vec, psite)
      index_vec <- c(index_vec, i)
      
    } else {
      
      psite <- paste(sub_seq[(pos-7):(pos+7)],collapse='')
      if (!substr(psite,8,8) %in% c('S','T','Y')) {next}
      psite_vec <- c(psite_vec, psite)
      index_vec <- c(index_vec, i)
      
    }
  } 
}

# Add psites to the table

csnk2a_ksr_psite <- cbind(csnk2a_ksr[index_vec,],psite_vec)
colnames(csnk2a_ksr_psite)[6] <- 'Sequence'

# Filter out redundant sites

supp_table_1 <- csnk2a_ksr_psite[!duplicated(csnk2a_ksr_psite[,c(3,4)]),]
write.csv(supp_table_1,file='Supplementary_table_1.csv',row.names = F)

```

# Model the specificity of CK2

```{r}

# After removing potential heirarchical sites

bachmann_vec <- psite_vec
p1s <- rapply(strsplit(psite_vec,split=''), function(x) x[9]) == 'S'
p3s <- rapply(strsplit(psite_vec,split=''), function(x) x[11]) == 'S'
psite_no_heira <- psite_vec[!(p1s|p3s)]

# Construct PWM using basic method for a sequence window from -6 to +6

source('match-tm.r')
csnk2_pwm <- makePWM(substr(psite_no_heira,2,14))
ggseqlogo(substr(psite_no_heira,2,14),method='probability')

# Negative charge scoring function (we ignore the phosphoacceptor here)

ED_weight <- function(psite,pwm) {
  
  neg_row <- apply(pwm[rownames(pwm) %in% c('D','E'),],2,sum)
  pwm <- pwm[!rownames(pwm) %in% c('D','E'),]
  pwm <- rbind(pwm,neg_row)
  rownames(pwm)[nrow(pwm)] <- 'DE'
  
  psite <- unlist(strsplit(psite,split=''))
  
  c=0
  min=0
  
  # Ignore the central residue
  for (i in c(1:6,8:13)) {
    
    aa <- psite[i]  
    if (aa %in% c('D','E')) {aa <- 'DE'}
    
    # Skip if the amino acid is not D or E
    if (!(aa %in% c('DE'))) {next}
    
    current <- pwm[rownames(pwm) %in% aa,i]
    c = c+current
  
  }
  
  maximum <- sum(pwm[rownames(pwm) == 'DE',][c(1:6,8:13)])
  mss = c/maximum
  
  return(unname(mss))
  
}

```

# Construct publication-ready PWM from the ProtMapper database

```{r}

source('match-tm.r')

publication_pwm <- makePWM(substr(psite_no_heira,2,14))[1:20,]
publication_pwm[!rownames(publication_pwm) %in% c('D','E'),!colnames(publication_pwm) %in% c(7)] <- 0
colnames(publication_pwm) <- -6:6

g <- ggseqlogo(publication_pwm, method='custom', seq_type='aa') + ylab('')
g <- g + theme(text=element_text(family="Ubuntu Light", face="plain", size=8))
g <- g + theme(legend.position = 'none') + ggtitle('')
g <- g+theme(plot.title = element_text(hjust = 0.5,size=18,face='plain'))
g <- g + theme(axis.text=element_text(size=12),axis.title=element_text(size=18,face="plain"),axis.text.y = element_blank())
g$scales$scales[[1]] <- scale_x_continuous(breaks=1:13,labels=colnames(publication_pwm))
g <- g+theme(plot.margin = unit(c(0,1.0,0.0,1.0), "cm"))
fig_1b <- g
fig_1b

ggsave(file='Figure_1B.pdf', plot=g, width=9, height=5.8)

```

# Relate CK2 substrate quality to the the phosphorylation stoichiometry measured in Tsai et al., 2015

```{r}

library(stringr)

Ishi <- read.xls('Ishihama_stoichiometry.xlsx',sheet=2, stringsAsFactors=FALSE)

## Exclude '0' stoichiometry sites

Ishi <- Ishi[!Ishi[,8] == 0,]
Ishi_CK2 <- Ishi[grep('CK2',Ishi[,18]),]

# Doubly phosphorylated peptides are confounders and need to be removed as stoichiometry measured reflects combined phosphorylation across both sites
Ishi_CK2 <- Ishi_CK2[!Ishi_CK2[,3] == '2 Phospho (ST)',]

# Substrate quality scoring function
ED_weight <- function(psite,pwm) {
  
  neg_row <- apply(pwm[rownames(pwm) %in% c('D','E'),],2,sum)
  pwm <- pwm[!rownames(pwm) %in% c('D','E'),]
  pwm <- rbind(pwm,neg_row)
  rownames(pwm)[nrow(pwm)] <- 'DE'
  
  psite <- unlist(strsplit(psite,split=''))
  
  c=0
  min=0
  
  # Ignore the central residue
  for (i in c(1:6,8:13)) {
    
    aa <- psite[i]  
    if (aa %in% c('D','E')) {aa <- 'DE'}
    
    # Skip if the amino acid is not D or E
    if (!(aa %in% c('DE'))) {next}
    
    current <- pwm[rownames(pwm) %in% aa,i]
    c = c+current
  
  }
  
  maximum <- sum(pwm[rownames(pwm) == 'DE',][c(1:6,8:13)])
  mss = c/maximum
  
  return(unname(mss))
  
}

# Score all non-hierarchical sites with the MSS and then plot

Ishi_CK2_stoi <- Ishi_CK2[,c(8,9)]

# Remove all potential heirarchical sites and T sites
p1s <- rapply(strsplit(Ishi_CK2_stoi[,2],split=''), function(x) x[8]) == 'S'
p3s <- rapply(strsplit(Ishi_CK2_stoi[,2],split=''), function(x) x[10]) == 'S'
p0t <- rapply(strsplit(Ishi_CK2_stoi[,2],split=''), function(x) x[7]) == 'T'
Ishi_CK2_stoi <- Ishi_CK2_stoi[!(p1s|p3s|p0t),]

# Score each one of the sites

mss_vec <- NULL

for (i in 1:nrow(Ishi_CK2_stoi)) {
  
  mss <- NULL
  ck2_site <- Ishi_CK2_stoi[i,2]
  mss <- ED_weight(ck2_site,csnk2_pwm)
  if (length(mss) == 0) {break}
  mss_vec <- c(mss_vec, mss)
  
}

Ishi_CK2_stoi <- cbind(Ishi_CK2_stoi, mss_vec)

### Generate GGplot boxplot

ED_list <- list()
col1 <- NULL
col2 <- NULL
col3 <- NULL

for (i in 0:9) {
  
  lower <- 0.1*i
  upper <- lower+0.1
  print(lower)
  print(upper)
  
  ED_stoi <- Ishi_CK2_stoi[Ishi_CK2_stoi[,3] > lower & Ishi_CK2_stoi[,3] <= upper,1]
  ED_stoi <- ED_stoi[!ED_stoi == 'NaN']
  ED_list <- c(ED_list, list(ED_stoi))
  
  col1 <- c(col1,ED_stoi)
  col2 <- c(col2,rep(paste(lower,'-',upper,sep=''),length(ED_stoi)))
  col3 <- c(col3,Ishi_CK2_stoi[Ishi_CK2_stoi[,3] > lower & Ishi_CK2_stoi[,3] <= upper,2])
}

mss_data <- data.frame(col1,col2,stringsAsFactors = FALSE)
mss_data[,2] <- as.factor(mss_data[,2])
colnames(mss_data) <- c('Stoichiometry','Positions')

p <- ggplot(mss_data, aes(x=Positions, y=Stoichiometry)) + geom_boxplot(fill='white',color=colors()[35], lwd=1.15, notch=FALSE,fatten=0.75) + geom_jitter(width = 0.2, color=colors()[35],size=0.6) 

# Font
p <- p+theme_bw() + theme(text=element_text(family="Ubuntu Light", face="plain", size=15), panel.border = element_rect(color="black", size=1.2, linetype="solid"))

# Ticks
p <- p+theme(axis.ticks.length=unit(-0.10, "cm"), axis.text.x = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")), axis.text.y = element_text(margin=unit(c(0.2,0.2,0.2,0.2), "cm")) )

p <- p + ylab("Stoichiometry") + xlab("Substrate quality") + ggtitle('')
p <- p + theme(axis.title.y = element_text(vjust=-1.5))
p <- p+theme(axis.text=element_text(size=7),axis.title.x=element_text(size=10,face="plain"),axis.title.y=element_text(size=11,face="plain"),plot.title=element_text(size=18,face='bold'))
p <- p+theme(plot.title = element_text(hjust = 0.5))
p <- p + theme(legend.position = "none") #  
p <- p + theme(plot.margin = unit(c(0,0,0.1,0), "cm")) # t, r, b, l
p <- p + theme(axis.text.x = element_text(angle = 30, vjust = 1.0, hjust=1))
fig_1e <- p

ggsave(file='Figure_1E.pdf', plot=p, width=6.0, height=4.8)

```
